/**:
  ros__parameters:
    tracker_ignore_label:
      UNKNOWN : true
      CAR : true
      TRUCK : false
      BUS : false
      TRAILER : false
      MOTORCYCLE : false
      BICYCLE : false
      PEDESTRIAN : false
